backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'TitleH1', name: 'titleH1', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Publish Date', name: 'publishDate', widget: 'datetime', required: false }
      - { label: 'Author', name: 'author', widget: 'string' }

      - { label: 'sec1', name: 'sec1', widget: 'string' }
      - { label: 'sec2', name: 'sec2', widget: 'string' }
      - { label: 'sec3', name: 'sec3', widget: 'string' }
      - { label: 'sec4', name: 'sec4', widget: 'string' }
      - { label: 'sec5', name: 'sec5', widget: 'string' }
      - { label: 'sec6', name: 'sec6', widget: 'string' }
      - { label: 'sec7', name: 'sec7', widget: 'string' }
      - { label: 'sec8', name: 'sec8', widget: 'string' }
      - { label: 'sec9', name: 'sec9', widget: 'string' }
      - { label: 'sec10', name: 'sec10', widget: 'string' }

      - { label: 'Content', name: 'body', widget: 'markdown' }
