site:
  name: Volet Spécialiste
  site: 'https://volet-specialiste.com/'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: google-site-verification=IA39K38MFcweIfiQrsCLbaoGgER0HovfYRjTF3aZG50

# Default SEO metadata
metadata:
  title:
    default: Volet Spécialiste
    template: '%s'
  description: "Obtenez des informations essentielles sur les volets roulants grâce à notre d'experts."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: Volet Spécialiste
    images:
      - url: '~/assets/images/volet-roulant-square-03.png'
        width: 950
        height: 350
    type: website
  twitter:
    handle: '@onwidget'
    site: '@onwidget'
    cardType: summary_large_image

i18n:
  language: fr
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: true

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'light:only' # Values: "system" | "light" | "dark" | "light:only" |

  tokens:
    default:
      fonts:
        sans: Lexend
        serif: var(--ph-font-sans)
        heading: var(--ph-font-sans)
      colors:
        default: rgb(16 16 16)
        heading: rgb(0 0 0)
        muted: rgb(40 40 40)
        bgPage: rgb(255 255 255)
        primary: rgb(0 124 220)
        secondary: rgb(30 58 138)
        accent: rgb(109 40 217)
        info: rgb(119 182 234)
        success: rgb(54 211 153)
        warning: rgb(251 189 35)
        error: rgb(248 114 114)
        link: var(--ph-color-primary)
        linkActive: var(--ph-color-link)
